apiVersion: app/v1
kind: Deployment
metadata:
  app: auth-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth-dep
    spec:
      containers:
        - name: auth
          image: dawit687/auth

---
apiVersion: v1
kind: Service
metadata:
  app: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      port: 3000
      targetPort: 3000
      protocol: TCP
